const { DataTypes } = require("sequelize");
const sequelize = require("../config/db").sequelize;

const Participant = sequelize.define("Participant", {
  _id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },
  activityId: {
    type: DataTypes.UUID,
    allowNull: false,
  },
  participantUserId: {
    type: DataTypes.UUID,
    allowNull: true, // null for anonymous (guest) participants
  },
  guestId: {
    type: DataTypes.STRING,
    allowNull: true, // random UUID generated by the frontend for anonymous users
  },
  displayName: {
    type: DataTypes.STRING,
    allowNull: false,
  },
  joinedAt: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW,
  },
}, {
  tableName: "participants",
  timestamps: true,
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  indexes: [
    {
      unique: true,
      fields: ["activityId", "guestId"],
    }
  ]
});

Participant.prototype.toObject = function() {
  return this.toJSON();
};

module.exports = Participant;
